# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeUsage < Formula
  desc "Know how much of your Claude.ai plan you've burned — from your terminal."
  homepage "https://github.com/tonydisco/claude-usage"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tonydisco/claude-usage/releases/download/v0.5.0/claude-usage_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "a4a4c24e84ed41644b9030b71f98fd4c57a738381ebfbe39c8d2442ccfd1dc80"

      define_method(:install) do
        bin.install "claude-usage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tonydisco/claude-usage/releases/download/v0.5.0/claude-usage_0.5.0_Darwin_arm64.tar.gz"
      sha256 "a4a9fe8ebd815cec46fdf018b90be4aff0cadd630a26f76507ec6e7ec8c83ba6"

      define_method(:install) do
        bin.install "claude-usage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonydisco/claude-usage/releases/download/v0.5.0/claude-usage_0.5.0_Linux_x86_64.tar.gz"
      sha256 "e8812faeaf4fd9cfcc6624f8fa4ae03ed937bf88ff8f7e5984d1106aeb4951fc"
      define_method(:install) do
        bin.install "claude-usage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonydisco/claude-usage/releases/download/v0.5.0/claude-usage_0.5.0_Linux_arm64.tar.gz"
      sha256 "d674919b9ca61606dd7b31de4a8cb20b3ce482c83e48e67a9b3bdcf3cd2dedff"
      define_method(:install) do
        bin.install "claude-usage"
      end
    end
  end

  test do
    system "#{bin}/claude-usage", "--help"
  end
end
