# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-usage" do
  version "0.6.7"

  on_macos do
    on_intel do
      sha256 "178133f8b98bf9f365b103eb84e0474ba090b14c07f616e0f7c2742768b26035"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5403ad528be4086ad0e29b5e4ad34556a59892e04bcd04d0fad45c282e09fe0f"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a271383907b609faaf680a97512e96ff16fe238a13b3921d41649df08b61d4f"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "daac5e6d0f3129e546e9bb6f279ac7523afe82f2854c9902aa62e39899d4403d"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "claude-usage"
  desc "Know how much of your Claude.ai plan you've burned — from your terminal."
  homepage "https://github.com/tonydisco/claude-usage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-usage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-usage"]
    end
  end

  # No zap stanza required

end
