# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-usage" do
  version "0.6.6"

  on_macos do
    on_intel do
      sha256 "de9e81e6b05a33b75283d01403d87cc1fd1a778dd359f1ed50a7eeeaa4b1c67c"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cd6d4638ba3a519e0670f6d08a1dcf69c3096f450b1083eda211c1021ba52812"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38f1cdc9404ec81bac94d4d551df68ab635772bd6492b94fe0fa6eefefccf74e"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1829e446e0555f311ae12906dc18a5e237c057fe5f8f1b3eac9783e20f4de94b"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "claude-usage"
  desc "Know how much of your Claude.ai plan you've burned — from your terminal."
  homepage "https://github.com/tonydisco/claude-usage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-usage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-usage"]
    end
  end

  # No zap stanza required

end
