# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-usage" do
  version "0.6.5"

  on_macos do
    on_intel do
      sha256 "0447751496e01f19fcbcff26a419ffcc144e27dbfa3cfcc8df9e80a043fa9c99"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3e323f7088b0128b28c020b26a28f03ff88eeca8083ba06eb95cb146472f4d7c"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30da40f8799f44fb97d2e83ae103eba10b29885a7df809a33a0424e42c57b67c"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c42a9d4816f26cffb5f70baf0612753a30e4a97ce3875226d7a0f83d8342d5a4"
      url "https://github.com/tonydisco/claude-usage/releases/download/v#{version}/claude-usage_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "claude-usage"
  desc "Know how much of your Claude.ai plan you've burned — from your terminal."
  homepage "https://github.com/tonydisco/claude-usage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-usage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-usage"]
    end
  end

  # No zap stanza required

end
